server:
    port: 9001
spring:
    config:
        name: ms-product
    datasource:
        driver-class-name: org.postgresql.Driver
        url: <url>
        username: <user>
        password: <password>